using Microsoft.CodeAnalysis;

namespace Reinterop
{
    /// <summary>
    /// A C# function that can be called from C++.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is used for:
    /// <list type="number">
    /// <item>Constructing C# classes.</item>
    /// <item>Calling C# methods from C++.</item>
    /// <item>Accessing C# properties from C++.</item>
    /// <item>Accessing C# fields from C++.</item>
    /// <item>Any other C# operation that is initiated from the C++ side.</item>
    /// </list>
    /// </para>
    /// <para>
    /// The code generated by this instance has several parts:
    /// <list type="number">
    /// <item>A C# delegate type declaration with a signature that is compatible with C++. For example, every class type is replaced by `IntPtr` (a `GCHandle`).</item>
    /// <item>A C# function with a signature that matches the delegate type. It has a custom implementation that does some work in C#.</item>
    /// <item>An instance of the C# delegate type that points to the C# function.</item>
    /// <item>Some code that creates a C++ function pointer from the delegate instance and passes it to C++.</item>
    /// <item>A C++ field that stores the function pointer created from the delegate.</item>
    /// <item>A C++ function that takes equivalent C++ types for each of the C# function's parameters, converts them as necessary, and calls through the function pointer.</item>
    /// </list>
    /// </para>
    /// <para>
    /// A large number of details are handled in the process. Exceptions thrown in C# are caught and rethrown in C++. Functions that return
    /// structs are rewritten to be returned via an "out" parameter. If this is conceptually an instance (non-static) function, an implicit "thiz"
    /// is passed as the first parameter. And more. The user of this class does not need to worry about any of these details.
    /// </para>
    /// <para>
    /// The generated C++ interop function may become a public member of the class. Or, it may be private and wrapped in a friendlier public API.
    /// Similarly, this instance may provide the entire C#-side implementation of the function, or it may simply call some other function for
    /// the bulk of the implementation. In both cases, the choice is up to the user of this class.
    /// </para>
    /// </remarks>
    internal class CSharpFunctionCallableFromCpp
    {
        public CSharpFunctionCallableFromCpp(CppGenerationContext context, CSharpType owner)
        {
            _context = context;
            _owner = owner;
            _returnType = new CSharpType(context, InteropTypeKind.Primitive, [], "void", SpecialType.System_Void);
        }

        public CSharpFunctionCallableFromCpp(CppGenerationContext context, ITypeSymbol owner)
            : this(context, CSharpType.FromSymbol(context, owner))
        {
        }

        private readonly CppGenerationContext _context;
        public CppGenerationContext Context() { return _context; }

        private CSharpType _owner;
        public CSharpType Owner() { return _owner; }

        private string? _name;
        public CSharpFunctionCallableFromCpp Name(string name) { _name = name; return this; }
        public string? Name() { return _name; }

        private CSharpType _returnType;
        /// <summary>
        /// Sets the function's return type. This should _not_ include any return type transformations, such as rewriting
        /// a struct return type to an "out" parameter. Those transformations are handled automatically by the generated
        /// interop function.
        /// </summary>
        public CSharpFunctionCallableFromCpp ReturnType(CSharpType returnType) { _returnType = returnType; return this; }
        /// <summary>
        /// Sets the function's return type. This should _not_ include any return type transformations, such as rewriting
        /// a struct return type to an "out" parameter. Those transformations are handled automatically by the generated
        /// interop function.
        /// </summary>
        public CSharpFunctionCallableFromCpp ReturnType(ITypeSymbol roslynType)
        {
            _returnType = CSharpType.FromSymbol(_context, roslynType);
            return this;
        }
        /// <summary>
        /// Gets the function's return type. This should _not_ include any return type transformations, such as rewriting
        /// a struct return type to an "out" parameter. Those transformations are handled automatically by the generated
        /// interop function.
        /// </summary>
        public CSharpType ReturnType() { return _returnType; }

        private List<CSharpParameter> _parameters = [];
        /// <summary>
        /// Sets the parameters to the function. This should _not_ include any parameter transformations, such
        /// as the implicit this pointer, the reinteropException parameter, or a rewritten out parameter for a
        /// struct return type. Those transformations are handled automatically by the generated interop function. 
        /// </summary>
        public CSharpFunctionCallableFromCpp Parameters(IEnumerable<CSharpParameter> parameters) { _parameters = parameters.ToList(); return this; }
        /// <summary>
        /// Sets the parameters to the function. This should _not_ include any parameter transformations, such
        /// as the implicit this pointer, the reinteropException parameter, or a rewritten out parameter for a
        /// struct return type. Those transformations are handled automatically by the generated interop function. 
        /// </summary>
        public CSharpFunctionCallableFromCpp Parameters(IEnumerable<IParameterSymbol> roslynParameters)
        {
            _parameters = roslynParameters.Select(p => new CSharpParameter(CSharpType.FromSymbol(_context, p.Type), p.Name)).ToList();
            return this;
        }
        /// <summary>
        /// Gets the parameters to the function. This should _not_ include any parameter transformations, such
        /// as the implicit this pointer, the reinteropException parameter, or a rewritten out parameter for a
        /// struct return type. Those transformations are handled automatically by the generated interop function. 
        /// </summary>
        public List<CSharpParameter> Parameters() { return _parameters; }

        private List<CSharpType> _typeArguments = [];
        /// <summary>
        /// Sets the generic type arguments to this function. Only concrete specializations of a generic function are
        /// callable from C++. If this function is not generic, this list will be empty. If it is generic, this list
        /// will contain the concrete type arguments for the specialization.
        /// </summary>
        public CSharpFunctionCallableFromCpp TypeArguments(IEnumerable<CSharpType> typeArguments) { _typeArguments = typeArguments.ToList(); return this; }
        /// <summary>
        /// Sets the generic type arguments to this function. Only concrete specializations of a generic function are
        /// callable from C++. If this function is not generic, this list will be empty. If it is generic, this list
        /// will contain the concrete type arguments for the specialization.
        /// </summary>
        public CSharpFunctionCallableFromCpp TypeArguments(IEnumerable<ITypeSymbol> roslynTypeArguments)
        {
            _typeArguments = roslynTypeArguments.Select(t => CSharpType.FromSymbol(_context, t)).ToList();
            return this;
        }
        /// <summary>
        /// Gets the generic type arguments to this function. Only concrete specializations of a generic function are
        /// callable from C++. If this function is not generic, this list will be empty. If it is generic, this list
        /// will contain the concrete type arguments for the specialization.
        /// </summary>
        public List<CSharpType> TypeArguments() { return _typeArguments; }

        private bool _private = false;
        /// <summary>
        /// Gets a value indicating whether this function is private. This controls whether the function's own declaration (not the interop function pointer field,
        /// which is always private) is marked as private in the generated C++ code.
        /// </summary>
        public bool Private() { return _private; }
        /// <summary>
        /// Sets a value indicating whether this function is private. This controls whether the function's own declaration (not the interop function pointer field,
        /// which is always private) is marked as private in the generated C++ code.
        /// </summary>
        public CSharpFunctionCallableFromCpp Private(bool isPrivate) { _private = isPrivate; return this; }

        private bool _static = false;
        /// <summary>
        /// Gets a value indicating whether this is a static member. `true` if it is static, `false` if it is an
        /// instance member that must be called with a "this" pointer. Note that constructors are considered
        /// static, since they don't have a "this" pointer yet.
        /// </summary>
        public bool Static() { return _static; }
        /// <summary>
        /// Sets a value indicating whether this is a static member. `true` if it is static, `false` if it is an
        /// instance member that must be called with a "this" pointer. Note that constructors are considered
        /// static, since they don't have a "this" pointer yet.
        /// </summary>
        public CSharpFunctionCallableFromCpp Static(bool isStatic) { _static = isStatic; return this; }

        public interface IGenerateCSharpBody
        {
            IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function);
        }

        /// <summary>
        /// An implementation of a C# interop function that invokes the method <see cref="CSharpFunctionCallableFromCpp.Name"/>
        /// on <see cref="CSharpFunctionCallableFromCpp.Owner"/>. It is called with <see cref="CSharpFunctionCallableFromCpp.Parameters"/>
        /// and expected to return <see cref="CSharpFunctionCallableFromCpp.ReturnType"/>. If
        /// <see cref="CSharpFunctionCallableFromCpp.Static"/> is `true`, the method is invoked as a static method; otherwise, it is
        /// invoked on an instance of <see cref="CSharpFunctionCallableFromCpp.Owner"/>. If
        /// <see cref="CSharpFunctionCallableFromCpp.TypeArguments"/> is not empty, the method is a generic method and is invoked with the
        /// specified type arguments.
        /// </summary>
        public class CSharpBodyInvokeMethod : IGenerateCSharpBody
        {
            public IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function)
            {
                CSharpExpression target = function.Static() ? new CSharpIdentifier(function.Owner().GetFullyQualifiedName()) : new CSharpIdentifier("thiz");
                CSharpCall callExpression = new CSharpCall(new CSharpMemberAccess(target, function.Name()!), function.Parameters().Select(p => new CSharpIdentifier(p.Name)).ToArray());
                if (function.ReturnType().SpecialType == SpecialType.System_Void)
                    yield return new CSharpExpressionStatement(callExpression);
                else
                    yield return new CSharpReturn(callExpression);
            }
        }

        /// <summary>
        /// An implementation of a C# interop function that invokes the binary operator identified by <see cref="CSharpFunctionCallableFromCpp.Name"/>
        /// with the left and right operands provided by <see cref="CSharpFunctionCallableFromCpp.Parameters"/>. There must be exactly two parameters.
        /// The operator is expected to return <see cref="CSharpFunctionCallableFromCpp.ReturnType"/>.
        /// </summary>
        public class CSharpBodyInvokeBinaryOperator : IGenerateCSharpBody
        {
            public IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function)
            {
                if (function.Parameters().Count != 2)
                    throw new InvalidOperationException("CSharpBodyInvokeBinaryOperator requires exactly two parameters.");

                CSharpExpression leftExpr = new CSharpIdentifier(function.Parameters()[0].Name);
                CSharpExpression rightExpr = new CSharpIdentifier(function.Parameters()[1].Name);
                yield return new CSharpReturn(new CSharpBinary(Interop.MethodNameToOperator(function.Name()!), leftExpr, rightExpr));
            }
        }

        private IGenerateCSharpBody? _body = null;

        public CSharpFunctionCallableFromCpp Body(IGenerateCSharpBody body)
        {
            _body = body;
            return this;
        }

        public IGenerateCSharpBody? Body() { return _body; }

        /// <summary>
        /// Determines if this function's return type necessitates rewriting the interop function to return via an out-parameter instead of directly.
        /// </summary>
        public bool NeedsStructReturnRewrite
        {
            get { return Interop.NeedsStructReturnRewrite(ReturnType()); }
        }

        public string GetUniqueFunctionName()
        {
            string name = Owner().GetFullyQualifiedName() + "." + Name();
            if (TypeArguments().Count > 0)
            {
                name += "<" + string.Join(",", TypeArguments().Select(t => t.GetFullyQualifiedName())) + ">";
            }
            return name;
        }

        public void GenerateCode(CppGenerationContext context, GeneratedResult result)
        {
            if (_name == null) 
                throw new InvalidOperationException("Cannot generate C# code for a CSharpFunctionCallableFromCpp because it has no Name.");

            CSharpType csOwner = Owner();
            CppType cppOwner = CppType.FromCSharp(context, csOwner);

            if (_body == null)
                throw new InvalidOperationException("Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetUniqueFunctionName()} because it has no body.");
            List<CSharpStatement> bodyStatements = _body.GenerateBody(context, this).ToList();
            if (bodyStatements.Count == 0)
                throw new InvalidOperationException("Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetUniqueFunctionName()} because it has an empty body.");

            // If this function returns a value, make sure all return statements return a value.
            // If it doesn't return a value, any return statement must have a null value.
            IEnumerable<CSharpReturn> returnStatements = bodyStatements.Select(statement => statement as CSharpReturn).Where(statement => statement != null).Select(statement => statement!);
            bool isVoidReturn = ReturnType().SpecialType == SpecialType.System_Void;
            if (isVoidReturn && returnStatements.Any(statement => statement.Value != null))
                throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetUniqueFunctionName()} because it has a void return type but has a non-void return statement.");
            else if (!isVoidReturn && returnStatements.Any(statement => statement.Value == null))
                throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetUniqueFunctionName()} because it has a non-void return type but has a void return statement.");        

            // Collect the C# and C++ types visible to their respective languages.
            List<CSharpParameter> csParameters = Parameters().ToList();
            CSharpType csReturnType = ReturnType();

            List<CppInteropParameter> cppParameters = Parameters().Select(parameter => new CppInteropParameter(parameter.Name, CppType.FromCSharp(context, parameter.Type))).ToList();
            CppType cppReturnType = CppType.FromCSharp(context, csReturnType);

            // Collect the C# and C++ types used at the interop boundary.
            List<CSharpParameter> csInteropParameters = csParameters.Select(parameter => new CSharpParameter(parameter.Type.AsInteropTypeParameter(), parameter.Name)).ToList();
            CSharpType csInteropReturnType = csReturnType.AsInteropTypeReturn();
            List<CppParameter> cppInteropParameters = cppParameters.Select(parameter => new CppParameter(parameter.Type.AsParameterType().AsInteropType(), parameter.Name)).ToList();
            CppType cppInteropReturnType = cppReturnType.AsReturnType().AsInteropType();

            // The C# statements that receive the interop parameters and convert them to the types expected by the body of the function.
            Dictionary<string, CSharpExpression> csInteropParameterConversions = new();
            foreach (CSharpParameter parameter in csParameters)
            {
                csInteropParameterConversions[parameter.Name] = parameter.Type.GetParameterConversionFromInteropTypeExpression(new CSharpIdentifier(parameter.Name));
            }
            
            // The C++ statements that receive the interop parameters converted from the external function parameters.
            List<CppVariableDeclaration> cppInteropParameterConversions = cppParameters.Select(parameter =>
                new CppVariableDeclaration(
                    parameter.Type.GetFullyQualifiedName(),
                    parameter.Name,
                    parameter.Type.GetConversionToInteropTypeExpression(context, parameter.Name + "_interop"))).ToList();

            // If this is an instance method, add an explicit `thiz` to the interop function's parameters.
            if (!Static())
            {
                csInteropParameters.Insert(0, new CSharpParameter(csOwner.AsInteropTypeParameter(), "thiz"));
                csInteropParameterConversions["thiz"] = csOwner.GetParameterConversionFromInteropTypeExpression(new CSharpIdentifier("thiz"));
                cppInteropParameters.Insert(0, new CppParameter(cppOwner.AsParameterType().AsInteropType(), "thiz"));
                cppInteropParameterConversions.Insert(0, new CppVariableDeclaration(cppOwner.GetFullyQualifiedName(), "thiz", cppOwner.GetConversionToInteropTypeExpression(context, "(*this)")));
            }

            // If this function requires a struct return rewrite, handle the necessary adjustments here.
            if (NeedsStructReturnRewrite)
            {
                csInteropParameters.Add(new CSharpParameter(csInteropReturnType.AsPointer(), "pReturnValue"));
                cppInteropParameters.Add(new CppParameter(cppInteropReturnType.AsPointer(), "pReturnValue"));

                CSharpStatement newReturnStatement;
                if (csReturnType.Kind == InteropTypeKind.Nullable)
                {
                    csInteropReturnType = CSharpType.FromSymbol(context, context.Compilation.GetSpecialType(SpecialType.System_Byte));
                    cppInteropReturnType = CppType.UInt8.AsReturnType();
                    newReturnStatement = new CSharpIf(
                        new CSharpBinary("!=", new CSharpIdentifier("returnValue_interop"), new CSharpLiteral("null")),
                        [
                            // Nullable has a value
                            new CSharpExpressionStatement(new CSharpBinary("=", new CSharpIdentifier("(*pReturnValue)"), new CSharpUnary("*", new CSharpIdentifier("returnValue_interop")))),
                            new CSharpReturn(new CSharpLiteral("1"))
                        ],
                        [
                            // Nullable does not have a value
                            new CSharpReturn(new CSharpLiteral("0"))
                        ]
                    );
                }
                else
                {
                    csInteropReturnType = CSharpType.FromSymbol(context, context.Compilation.GetSpecialType(SpecialType.System_Void));
                    cppInteropReturnType = CppType.Void.AsReturnType();
                    newReturnStatement = new CSharpExpressionStatement(new CSharpBinary(
                        "=",
                        new CSharpUnary("*", new CSharpIdentifier("pReturnValue")),
                        new CSharpIdentifier("returnValue_interop")
                    ));
                }

                bodyStatements = RewriteStructReturn(bodyStatements, csReturnType, "returnValue_interop", newReturnStatement);
            }

            // Rewrite the body to convert from the interop parameter types to the C# parameter types, and
            // from the C# return type to the interop return type.
            if (csReturnType.SpecialType != SpecialType.System_Void)
                bodyStatements = RewriteReturnStatementToConvertToInterop(bodyStatements, csReturnType, csInteropReturnType);
            if (csInteropParameterConversions.Count > 0)
                bodyStatements = RewriteParametersToConvertFromInterop(bodyStatements, csInteropParameterConversions);

            // Always add an additional parameter for exception handling.
            CSharpType csInteropExceptionType = CSharpType.FromSymbol(context, context.Compilation.GetSpecialType(SpecialType.System_IntPtr)).AsPointer();
            CppType cppInteropExceptionType = CppType.VoidPointerPointer.AsParameterType();
            csInteropParameters.Add(new CSharpParameter(csInteropExceptionType, "reinteropException"));
            cppInteropParameters.Add(new CppParameter(cppInteropExceptionType, "reinteropException"));
            
            // Wrap the entire body in an exception handler
            CSharpReturn csReturnOnException;
            if (csInteropReturnType.SpecialType == SpecialType.System_Void)
                csReturnOnException = new CSharpReturn(null);
            else if (csInteropReturnType.Flags.HasFlag(CSharpTypeFlags.Pointer) || csInteropReturnType.Kind == InteropTypeKind.ClassWrapper)
                csReturnOnException = new CSharpReturn(new CSharpLiteral("null"));
            else
                csReturnOnException = new CSharpReturn(new CSharpNew(csInteropReturnType.GetFullyQualifiedName(), []));

            bodyStatements = [
                new CSharpTryCatch(
                    bodyStatements,
                    [
                        new CSharpExpressionStatement(new CSharpBinary(
                            "=",
                            new CSharpUnary("*", new CSharpIdentifier("reinteropException")),
                            new CSharpCall(new CSharpMemberAccess(new CSharpIdentifier("Reinterop.ObjectHandleUtility"), "CreateHandle"), [new CSharpIdentifier("reinteropManagedException")])
                        )),
                        csReturnOnException
                    ]
                )
            ];

            string baseName = "Reinterop_" + Interop.GetUniqueNameForType(csOwner) + "_" + Interop.MakeSafeIdentifier(_name) + "_" +Interop.HashParameters(_parameters, _typeArguments);

            string interopParameterList = string.Join(", ", csInteropParameters.Select(p => p.Type.GetFullyQualifiedName() + " " + p.Name));
            string cppInteropParameterTypeList = string.Join(", ", cppInteropParameters.Select(p => p.Type.GetFullyQualifiedName()));
            IEnumerable<CppType> fieldPointerTypes = cppInteropParameters.Select(p => p.Type).Concat([ cppInteropReturnType ]);

            result.CppDeclaration.Elements.Add(new(
                Content: $"static {cppInteropReturnType.GetFullyQualifiedName()} (*{baseName})({cppInteropParameterTypeList});",
                IsPrivate: true,
                TypeDeclarationsReferenced: fieldPointerTypes));

            result.Init.Functions.Add(new GeneratedInitFunction(
                $"{cppOwner.GetFullyQualifiedName()}::{baseName}",
                $"{cppInteropReturnType.GetFullyQualifiedName()} (*)({cppInteropParameterTypeList})",
                baseName + "_Delegate",
                $$"""
                [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
                private unsafe delegate {{csInteropReturnType.GetFullyQualifiedName()}} {{baseName}}_Type({{interopParameterList}});
                private static unsafe readonly {{baseName}}_Type {{baseName}}_Delegate = new {{baseName}}_Type({{baseName}});
                [AOT.MonoPInvokeCallback(typeof({{baseName}}_Type))]
                private static unsafe {{csInteropReturnType.GetFullyQualifiedName()}} {{baseName}}({{interopParameterList}})
                {
                    {{CSharpPrinter.Print(bodyStatements, "    ")}}
                }
                """,
                CppTypeDeclarationsReferenced: fieldPointerTypes,
                CppTypeDefinitionsReferenced: [ cppOwner ]
            ));
        }

        // Rewrites return statements to convert the actual C# return value to its interop form.
        private List<CSharpStatement> RewriteReturnStatementToConvertToInterop(IEnumerable<CSharpStatement> statements, CSharpType returnType, CSharpType interopReturnType)
        {
            List<CSharpStatement> result = statements.Select(statement =>
            {
                return statement switch
                {
                    CSharpReturn r => new CSharpReturn(returnType.GetConversionToInteropTypeExpression(r.Value!)),
                    CSharpIf i => new CSharpIf(i.Condition, RewriteReturnStatementToConvertToInterop(i.Then, returnType, interopReturnType)),
                    CSharpStatement s => s
                };
            }).ToList();
            return result;
        }

        private List<CSharpStatement> RewriteParametersToConvertFromInterop(IEnumerable<CSharpStatement> statements, Dictionary<string, CSharpExpression> parameterConversions)
        {
            List<CSharpStatement> result = statements.Select(statement =>
            {
                return statement switch
                {
                    CSharpVariableDeclaration d => new CSharpVariableDeclaration(d.TypeName, d.Name, RewriteExpressionToConvertFromInterop(d.Initializer, parameterConversions)),
                    CSharpExpressionStatement s => new CSharpExpressionStatement(RewriteExpressionToConvertFromInterop(s.Expression, parameterConversions)!),
                    CSharpIf i => new CSharpIf(i.Condition, RewriteParametersToConvertFromInterop(i.Then, parameterConversions)),
                    CSharpThrow t => new CSharpThrow(RewriteExpressionToConvertFromInterop(t.Exception, parameterConversions)!),
                    CSharpReturn r => new CSharpReturn(RewriteExpressionToConvertFromInterop(r.Value, parameterConversions)),
                    CSharpTryCatch t => new CSharpTryCatch(RewriteParametersToConvertFromInterop(t.TryBody, parameterConversions), RewriteParametersToConvertFromInterop(t.CatchBody, parameterConversions)),
                    _ => statement
                };
            }).ToList();
            return result;
        }

        private CSharpExpression? RewriteExpressionToConvertFromInterop(CSharpExpression? expression, Dictionary<string, CSharpExpression> parameterConversions)
        {
            if (expression == null)
                return null;

            return expression switch
            {
                CSharpIdentifier i => RewriteIdentifierToConvertFromInterop(i, parameterConversions),
                CSharpCall c => new CSharpCall(RewriteExpressionToConvertFromInterop(c.Callee, parameterConversions)!, c.Arguments.Select(a => RewriteExpressionToConvertFromInterop(a, parameterConversions)!).ToArray()),
                CSharpTernary t => new CSharpTernary(RewriteExpressionToConvertFromInterop(t.Condition, parameterConversions)!, RewriteExpressionToConvertFromInterop(t.Then, parameterConversions)!, RewriteExpressionToConvertFromInterop(t.Else, parameterConversions)!),
                CSharpBinary b => new CSharpBinary(b.Op, RewriteExpressionToConvertFromInterop(b.Left, parameterConversions)!, RewriteExpressionToConvertFromInterop(b.Right, parameterConversions)!),
                CSharpUnary u => new CSharpUnary(u.Op, RewriteExpressionToConvertFromInterop(u.Operand, parameterConversions)!),
                CSharpIs i => new CSharpIs(RewriteExpressionToConvertFromInterop(i.Expression, parameterConversions)!, i.TypeName, i.castedVariableName),
                CSharpMemberAccess m => new CSharpMemberAccess(RewriteExpressionToConvertFromInterop(m.Target, parameterConversions)!, m.MemberName),
                CSharpNew n => new CSharpNew(n.TypeName, n.Arguments.Select(a => RewriteExpressionToConvertFromInterop(a, parameterConversions)!).ToArray()),
                CSharpCast c => new CSharpCast(c.TypeName, RewriteExpressionToConvertFromInterop(c.Expression, parameterConversions)!),
                _ => expression
            };
        }

        private CSharpExpression RewriteIdentifierToConvertFromInterop(CSharpIdentifier identifier, Dictionary<string, CSharpExpression> parameterConversions)
        {
            if (!parameterConversions.TryGetValue(identifier.Name, out CSharpExpression? conversion))
                return identifier;
            return conversion;
        }

        // Rewrites a C# function body like this:
        //   return thiz.SomeFunction(whatever);
        // into a body like this:
        //   SomeType returnValue_interop = thiz.SomeFunction(whatever);
        //   *pReturnValue = returnValue;
        // Where "returnValue_interop" is the string passed to the `returnValueName parameter, and "*pReturnValue = returnValue" is the statement passed
        // to the `newReturnStatement` parameter.
        // This function handles more complicated bodies with multiple return statements (e.g., if statements), and will throw an exception if it
        // encounters a return statement that doesn't return a value when the function has a non-void return type.
        private List<CSharpStatement> RewriteStructReturn(IEnumerable<CSharpStatement> statements, CSharpType returnType, string returnValueName, CSharpStatement newReturnStatement)
        {
            List<CSharpStatement> result = statements.SelectMany(statement =>
            {
                return statement switch
                {
                    CSharpReturn { Value: null } => throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetUniqueFunctionName()} because it has a struct return type but has a void return statement."),
                    CSharpReturn r => new List<CSharpStatement> {
                        new CSharpVariableDeclaration(returnType.GetFullyQualifiedName(), returnValueName, r.Value),
                        newReturnStatement
                    },
                    CSharpIf i => [new CSharpIf(i.Condition, RewriteStructReturn(i.Then, returnType, returnValueName, newReturnStatement))],
                    CSharpStatement s => [s]
                };
            }).ToList();
            return result;
        }
    }
}
