using Microsoft.CodeAnalysis;

namespace Reinterop
{
    /// <summary>
    /// A C# function that can be called from C++.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is used for:
    /// <list type="number">
    /// <item>Constructing C# classes.</item>
    /// <item>Calling C# methods from C++.</item>
    /// <item>Accessing C# properties from C++.</item>
    /// <item>Accessing C# fields from C++.</item>
    /// <item>Any other C# operation that is initiated from the C++ side.</item>
    /// </list>
    /// </para>
    /// <para>
    /// The code generated by this instance has several parts:
    /// <list type="number">
    /// <item>A C# delegate type declaration with a signature that is compatible with C++. For example, every class type is replaced by `IntPtr` (a `GCHandle`).</item>
    /// <item>A C# function with a signature that matches the delegate type. It has a custom implementation that does some work in C#.</item>
    /// <item>An instance of the C# delegate type that points to the C# function.</item>
    /// <item>Some code that creates a C++ function pointer from the delegate instance and passes it to C++.</item>
    /// <item>A C++ field that stores the function pointer created from the delegate.</item>
    /// <item>A C++ function that takes equivalent C++ types for each of the C# function's parameters, converts them as necessary, and calls through the function pointer.</item>
    /// </list>
    /// </para>
    /// <para>
    /// A large number of details are handled in the process. Exceptions thrown in C# are caught and rethrown in C++. Functions that return
    /// structs are rewritten to be returned via an "out" parameter. If this is conceptually an instance (non-static) function, an implicit "thiz"
    /// is passed as the first parameter. And more. The user of this class does not need to worry about any of these details.
    /// </para>
    /// <para>
    /// The generated C++ interop function may become a public member of the class. Or, it may be private and wrapped in a friendlier public API.
    /// Similarly, this instance may provide the entire C#-side implementation of the function, or it may simply call some other function for
    /// the bulk of the implementation. In both cases, the choice is up to the user of this class.
    /// </para>
    /// </remarks>
    internal class CSharpFunctionCallableFromCpp
    {
        public CSharpFunctionCallableFromCpp(CppGenerationContext context, CSharpType owner)
        {
            _context = context;
            _owner = owner;
            _returnType = new CSharpType(context, InteropTypeKind.Primitive, [], "void", SpecialType.System_Void);
        }

        public CSharpFunctionCallableFromCpp(CppGenerationContext context, ITypeSymbol owner)
            : this(context, CSharpType.FromSymbol(context, owner))
        {
        }

        private readonly CppGenerationContext _context;
        public CppGenerationContext Context() { return _context; }

        private CSharpType _owner;
        public CSharpType Owner() { return _owner; }

        private string? _name;
        public CSharpFunctionCallableFromCpp Name(string name) { _name = name; return this; }
        public string? Name() { return _name; }

        private CSharpType _returnType;
        /// <summary>
        /// Sets the function's return type. This should _not_ include any return type transformations, such as rewriting
        /// a struct return type to an "out" parameter. Those transformations are handled automatically by the generated
        /// interop function.
        /// </summary>
        public CSharpFunctionCallableFromCpp ReturnType(CSharpType returnType) { _returnType = returnType; return this; }
        /// <summary>
        /// Sets the function's return type. This should _not_ include any return type transformations, such as rewriting
        /// a struct return type to an "out" parameter. Those transformations are handled automatically by the generated
        /// interop function.
        /// </summary>
        public CSharpFunctionCallableFromCpp ReturnType(ITypeSymbol roslynType)
        {
            _returnType = CSharpType.FromSymbol(_context, roslynType);
            return this;
        }
        /// <summary>
        /// Gets the function's return type. This should _not_ include any return type transformations, such as rewriting
        /// a struct return type to an "out" parameter. Those transformations are handled automatically by the generated
        /// interop function.
        /// </summary>
        public CSharpType ReturnType() { return _returnType; }

        private List<CSharpParameter> _parameters = [];
        /// <summary>
        /// Sets the parameters to the function. This should _not_ include any parameter transformations, such
        /// as the implicit this pointer, the reinteropException parameter, or a rewritten out parameter for a
        /// struct return type. Those transformations are handled automatically by the generated interop function. 
        /// </summary>
        public CSharpFunctionCallableFromCpp Parameters(IEnumerable<CSharpParameter> parameters) { _parameters = parameters.ToList(); return this; }
        /// <summary>
        /// Sets the parameters to the function. This should _not_ include any parameter transformations, such
        /// as the implicit this pointer, the reinteropException parameter, or a rewritten out parameter for a
        /// struct return type. Those transformations are handled automatically by the generated interop function. 
        /// </summary>
        public CSharpFunctionCallableFromCpp Parameters(IEnumerable<IParameterSymbol> roslynParameters)
        {
            _parameters = roslynParameters.Select(p => new CSharpParameter(CSharpType.FromSymbol(_context, p.Type), p.Name)).ToList();
            return this;
        }
        /// <summary>
        /// Gets the parameters to the function. This should _not_ include any parameter transformations, such
        /// as the implicit this pointer, the reinteropException parameter, or a rewritten out parameter for a
        /// struct return type. Those transformations are handled automatically by the generated interop function. 
        /// </summary>
        public List<CSharpParameter> Parameters() { return _parameters; }

        private List<CSharpType> _typeArguments = [];
        /// <summary>
        /// Sets the generic type arguments to this function. Only concrete specializations of a generic function are
        /// callable from C++. If this function is not generic, this list will be empty. If it is generic, this list
        /// will contain the concrete type arguments for the specialization.
        /// </summary>
        public CSharpFunctionCallableFromCpp TypeArguments(IEnumerable<CSharpType> typeArguments) { _typeArguments = typeArguments.ToList(); return this; }
        /// <summary>
        /// Sets the generic type arguments to this function. Only concrete specializations of a generic function are
        /// callable from C++. If this function is not generic, this list will be empty. If it is generic, this list
        /// will contain the concrete type arguments for the specialization.
        /// </summary>
        public CSharpFunctionCallableFromCpp TypeArguments(IEnumerable<ITypeSymbol> roslynTypeArguments)
        {
            _typeArguments = roslynTypeArguments.Select(t => CSharpType.FromSymbol(_context, t)).ToList();
            return this;
        }
        /// <summary>
        /// Gets the generic type arguments to this function. Only concrete specializations of a generic function are
        /// callable from C++. If this function is not generic, this list will be empty. If it is generic, this list
        /// will contain the concrete type arguments for the specialization.
        /// </summary>
        public List<CSharpType> TypeArguments() { return _typeArguments; }

        private bool _private = false;
        /// <summary>
        /// Gets a value indicating whether this function is private. This controls whether the function's own declaration (not the interop function pointer field,
        /// which is always private) is marked as private in the generated C++ code.
        /// </summary>
        public bool Private() { return _private; }
        /// <summary>
        /// Sets a value indicating whether this function is private. This controls whether the function's own declaration (not the interop function pointer field,
        /// which is always private) is marked as private in the generated C++ code.
        /// </summary>
        public CSharpFunctionCallableFromCpp Private(bool isPrivate) { _private = isPrivate; return this; }

        private bool _static = false;
        /// <summary>
        /// Gets a value indicating whether this is a static member. `true` if it is static, `false` if it is an
        /// instance member that must be called with a "this" pointer. Note that constructors are considered
        /// static, since they don't have a "this" pointer yet.
        /// </summary>
        public bool Static() { return _static; }
        /// <summary>
        /// Sets a value indicating whether this is a static member. `true` if it is static, `false` if it is an
        /// instance member that must be called with a "this" pointer. Note that constructors are considered
        /// static, since they don't have a "this" pointer yet.
        /// </summary>
        public CSharpFunctionCallableFromCpp Static(bool isStatic) { _static = isStatic; return this; }

        private CppFunction? _specializes = null;
        /// <summary>
        /// Gets the generic template declaration that this function's C++ wrapper specializes, if any. A generic
        /// method is exposed to C++ as a bare <see cref="CppFunction"/> template declaration (it has no body of its
        /// own, since it can't be called without concrete type arguments), while each concrete instantiation is a
        /// <see cref="CSharpFunctionCallableFromCpp"/> whose C++ wrapper specializes that declaration and therefore
        /// doesn't get a declaration of its own - just a definition reusing the template's declaration. This is
        /// unset for a non-generic function.
        /// </summary>
        public CppFunction? Specializes() { return _specializes; }
        /// <summary>
        /// Sets the generic template declaration that this function's C++ wrapper specializes. See
        /// <see cref="Specializes()"/> for details.
        /// </summary>
        public CSharpFunctionCallableFromCpp Specializes(CppFunction? specializes) { _specializes = specializes; return this; }

        public interface IGenerateCSharpBody
        {
            IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function);
        }

        /// <summary>
        /// An implementation of a C# interop function that invokes the method <see cref="CSharpFunctionCallableFromCpp.Name"/>
        /// on <see cref="CSharpFunctionCallableFromCpp.Owner"/>. It is called with <see cref="CSharpFunctionCallableFromCpp.Parameters"/>
        /// and expected to return <see cref="CSharpFunctionCallableFromCpp.ReturnType"/>. If
        /// <see cref="CSharpFunctionCallableFromCpp.Static"/> is `true`, the method is invoked as a static method; otherwise, it is
        /// invoked on an instance of <see cref="CSharpFunctionCallableFromCpp.Owner"/>. If
        /// <see cref="CSharpFunctionCallableFromCpp.TypeArguments"/> is not empty, the method is a generic method and is invoked with the
        /// specified type arguments.
        /// </summary>
        public class CSharpBodyInvokeMethod : IGenerateCSharpBody
        {
            public IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function)
            {
                CSharpExpression target = function.Static() ? new CSharpIdentifier(function.Owner().GetFullyQualifiedName()) : new CSharpIdentifier("thiz");
                CSharpCall callExpression = new CSharpCall(new CSharpMemberAccess(target, function.Name()!), function.Parameters().Select(p => new CSharpIdentifier(p.Name)).ToArray());
                if (function.ReturnType().SpecialType == SpecialType.System_Void)
                    yield return new CSharpExpressionStatement(callExpression);
                else
                    yield return new CSharpReturn(callExpression);
            }
        }

        /// <summary>
        /// An implementation of a C# interop function that constructs and returns an instance of
        /// <see cref="CSharpFunctionCallableFromCpp.Owner"/> using
        /// <see cref="CSharpFunctionCallableFromCpp.Parameters"/>.
        /// </summary>
        public class CSharpBodyInvokeConstructor : IGenerateCSharpBody
        {
            public IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function)
            {
                yield return new CSharpReturn(new CSharpNew(
                    function.Owner().GetFullyQualifiedName(),
                    function.Parameters().Select(p => new CSharpIdentifier(p.Name)).ToArray()));
            }
        }

        /// <summary>
        /// An implementation of a C# interop function that invokes a property accessor using
        /// property or indexer syntax.
        /// </summary>
        public class CSharpBodyInvokePropertyAccessor : IGenerateCSharpBody
        {
            private readonly IPropertySymbol _property;
            private readonly bool _isGetter;

            public CSharpBodyInvokePropertyAccessor(IPropertySymbol property, bool isGetter)
            {
                _property = property;
                _isGetter = isGetter;
            }

            public IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function)
            {
                CSharpExpression target = function.Static() ? new CSharpIdentifier(function.Owner().GetFullyQualifiedName()) : new CSharpIdentifier("thiz");
                CSharpExpression accessor = _property.IsIndexer
                    ? new CSharpElementAccess(target, function.Parameters().Take(_property.Parameters.Length).Select(p => new CSharpIdentifier(p.Name)).ToArray())
                    : new CSharpMemberAccess(target, _property.Name);

                if (_isGetter)
                    yield return new CSharpReturn(accessor);
                else
                    yield return new CSharpExpressionStatement(new CSharpBinary("=", accessor, new CSharpIdentifier(function.Parameters().Last().Name)));
            }
        }

        /// <summary>
        /// An implementation of a C# interop function that reads or writes a field. Non-blittable
        /// structs are unboxed before access and written back to their handle afterwards.
        /// </summary>
        public class CSharpBodyInvokeFieldAccessor : IGenerateCSharpBody
        {
            private readonly IFieldSymbol _field;
            private readonly bool _isGetter;

            public CSharpBodyInvokeFieldAccessor(IFieldSymbol field, bool isGetter)
            {
                _field = field;
                _isGetter = isGetter;
            }

            public IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function)
            {
                CSharpExpression target;
                if (!function.Static() && function.Owner().Kind == InteropTypeKind.NonBlittableStructWrapper)
                {
                    const string unboxedReceiverName = "thizUnboxed";
                    yield return new CSharpVariableDeclaration(
                        function.Owner().GetFullyQualifiedName(),
                        unboxedReceiverName,
                        function.Owner().GetParameterConversionFromInteropTypeExpression(new CSharpRaw("thiz")));
                    target = new CSharpIdentifier(unboxedReceiverName);
                }
                else
                {
                    target = function.Static() ? new CSharpIdentifier(function.Owner().GetFullyQualifiedName()) : new CSharpIdentifier("thiz");
                }

                CSharpExpression accessor = new CSharpMemberAccess(target, _field.Name);
                if (_isGetter && function.Owner().Kind == InteropTypeKind.NonBlittableStructWrapper && !function.Static())
                {
                    const string returnValueName = "returnValue";
                    CSharpType fieldType = CSharpType.FromSymbol(context, _field.Type);
                    yield return new CSharpVariableDeclaration(fieldType.GetFullyQualifiedName(), returnValueName, accessor);
                    yield return ResetUnboxedReceiver();
                    yield return new CSharpReturn(new CSharpIdentifier(returnValueName));
                    yield break;
                }

                if (_isGetter)
                {
                    yield return new CSharpReturn(accessor);
                    yield break;
                }

                yield return new CSharpExpressionStatement(new CSharpBinary("=", accessor, new CSharpIdentifier(function.Parameters().Single().Name)));
                if (function.Owner().Kind == InteropTypeKind.NonBlittableStructWrapper && !function.Static())
                    yield return ResetUnboxedReceiver();
            }

            private static CSharpExpressionStatement ResetUnboxedReceiver()
            {
                return new CSharpExpressionStatement(new CSharpCall(
                    new CSharpMemberAccess(new CSharpIdentifier("Reinterop.ObjectHandleUtility"), "ResetHandleObject"),
                    [new CSharpRaw("thiz"), new CSharpIdentifier("thizUnboxed")]));
            }
        }

        /// <summary>
        /// An implementation of a C# interop function that invokes the binary operator identified by <see cref="CSharpFunctionCallableFromCpp.Name"/>
        /// with the left and right operands provided by <see cref="CSharpFunctionCallableFromCpp.Parameters"/>. There must be exactly two parameters.
        /// The operator is expected to return <see cref="CSharpFunctionCallableFromCpp.ReturnType"/>.
        /// </summary>
        public class CSharpBodyInvokeBinaryOperator : IGenerateCSharpBody
        {
            public IEnumerable<CSharpStatement> GenerateBody(CppGenerationContext context, CSharpFunctionCallableFromCpp function)
            {
                if (function.Parameters().Count != 2)
                    throw new InvalidOperationException("CSharpBodyInvokeBinaryOperator requires exactly two parameters.");

                CSharpExpression leftExpr = new CSharpIdentifier(function.Parameters()[0].Name);
                CSharpExpression rightExpr = new CSharpIdentifier(function.Parameters()[1].Name);
                yield return new CSharpReturn(new CSharpBinary(Interop.MethodNameToOperator(function.Name()!), leftExpr, rightExpr));
            }
        }

        private IGenerateCSharpBody? _body = null;

        public CSharpFunctionCallableFromCpp Body(IGenerateCSharpBody body)
        {
            _body = body;
            return this;
        }

        public IGenerateCSharpBody? Body() { return _body; }

        /// <summary>
        /// Determines if this function's return type necessitates rewriting the interop function to return via an out-parameter instead of directly.
        /// </summary>
        public bool NeedsStructReturnRewrite
        {
            get { return Interop.NeedsStructReturnRewrite(ReturnType()); }
        }

        public string GetDisplayName()
        {
            string name = Owner().GetFullyQualifiedName() + "." + Name();
            if (TypeArguments().Count > 0)
            {
                name += "<" + string.Join(",", TypeArguments().Select(t => t.GetFullyQualifiedName())) + ">";
            }
            return name;
        }

        public struct InteropFunctions
        {
            public CSharpFunction csharp;
            public CppFunction cpp;
            public CppFunction functionPointer;
        }

        /// <summary>
        /// Creates a pair of functions - one in C# and one in C++ - that work together to enable interop between the two languages.
        /// The C++ function takes the C++ equivalent of the <see cref="Parameters"/> and returns the C++ equivalent of the
        /// <see cref="ReturnType"/>. It is implemented to transform the parameters as necessary for interop, call through a
        /// function pointer into the paired C# function, and return the result back to the C++ caller. All of the interop details
        /// are handled internally, including exception handling and parameter rewriting. The C# function is implemented as
        /// specified in the <see cref="Body"/>.
        /// </summary>
        public InteropFunctions CreatePairedInteropFunctions()
        {
            if (_name == null) 
                throw new InvalidOperationException("Cannot generate paired functions for a CSharpFunctionCallableFromCpp because it has no Name.");

            CSharpType csOwner = Owner();
            CppType cppOwner = CppType.FromCSharp(_context, csOwner);

            if (_body == null)
                throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetDisplayName()} because it has no body.");
            List<CSharpStatement> bodyStatements = _body.GenerateBody(_context, this).ToList();
            if (bodyStatements.Count == 0)
                throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetDisplayName()} because it has an empty body.");

            // If this function returns a value, make sure all return statements return a value.
            // If it doesn't return a value, any return statement must have a null value.
            IEnumerable<CSharpReturn> returnStatements = bodyStatements.Select(statement => statement as CSharpReturn).Where(statement => statement != null).Select(statement => statement!);
            bool isVoidReturn = ReturnType().SpecialType == SpecialType.System_Void;
            if (isVoidReturn && returnStatements.Any(statement => statement.Value != null))
                throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetDisplayName()} because it has a void return type but has a non-void return statement.");
            else if (!isVoidReturn && returnStatements.Any(statement => statement.Value == null))
                throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetDisplayName()} because it has a non-void return type but has a void return statement.");        

            // Collect the C# and C++ types visible to their respective languages.
            List<CSharpParameter> csParameters = Parameters().ToList();
            CSharpType csReturnType = ReturnType();

            List<CppParameter> cppParameters = Parameters().Select(parameter => new CppParameter(CppType.FromCSharp(_context, parameter.Type), parameter.Name)).ToList();
            CppType cppReturnType = CppType.FromCSharp(_context, csReturnType);

            // Collect the C# and C++ types used at the interop boundary.
            List<CSharpParameter> csInteropParameters = csParameters.Select(parameter => new CSharpParameter(parameter.Type.AsInteropTypeParameter(), parameter.Name)).ToList();
            CSharpType csInteropReturnType = csReturnType.AsInteropTypeReturn();
            List<CppParameter> cppInteropParameters = cppParameters.Select(parameter => new CppParameter(parameter.Type.AsParameterType().AsInteropType(), parameter.Name)).ToList();
            CppType cppInteropReturnType = cppReturnType.AsReturnType().AsInteropType();

            // The C# statements that receive the interop parameters and convert them to the types expected by the body of the function.
            Dictionary<string, CSharpExpression> csInteropParameterConversions = new();
            foreach (CSharpParameter parameter in csParameters)
            {
                csInteropParameterConversions[parameter.Name] = parameter.Type.GetParameterConversionFromInteropTypeExpression(new CSharpIdentifier(parameter.Name));
            }
            
            string csFunctionName = "Reinterop_" + Interop.GetUniqueNameForType(csOwner) + "_" + Interop.MakeSafeIdentifier(_name) + "_" +Interop.HashParameters(_parameters, _typeArguments);

            List<CppExpression> cppCallArguments = cppParameters.Select(parameter => parameter.Type.GetConversionToInteropTypeExpression(_context, parameter.Name)).ToList();

            // If this is an instance method, add an explicit `thiz` to the interop function's parameters.
            if (!Static())
            {
                csInteropParameters.Insert(0, new CSharpParameter(csOwner.AsInteropTypeParameter(), "thiz"));
                csInteropParameterConversions["thiz"] = csOwner.GetParameterConversionFromInteropTypeExpression(new CSharpIdentifier("thiz"));
                cppInteropParameters.Insert(0, new CppParameter(cppOwner.AsParameterType().AsInteropType(), "thiz"));
                cppCallArguments.Insert(0, cppOwner.GetConversionToInteropTypeExpression(_context, "(*this)"));
            }

            List<CppStatement> cppBody = new();

            // If this function requires a struct return rewrite, handle the necessary adjustments here.
            if (NeedsStructReturnRewrite)
            {
                csInteropParameters.Add(new CSharpParameter(csInteropReturnType.AsPointer(), "pReturnValue"));
                cppInteropParameters.Add(new CppParameter(cppInteropReturnType.AsPointer(), "pReturnValue"));

                cppBody.Add(new CppVariableDeclaration(
                    cppInteropReturnType.GetFullyQualifiedName(),
                    "reinterop_returnValue"
                ));
                cppCallArguments.Add(new CppUnary("&", new CppIdentifier("reinterop_returnValue")));

                CSharpStatement newReturnStatement;
                if (csReturnType.Kind == InteropTypeKind.Nullable)
                {
                    csInteropReturnType = CSharpType.FromSymbol(_context, _context.Compilation.GetSpecialType(SpecialType.System_Byte));
                    cppInteropReturnType = CppType.UInt8.AsReturnType();
                    newReturnStatement = new CSharpIf(
                        new CSharpBinary("!=", new CSharpIdentifier("returnValue_interop"), new CSharpLiteral("null")),
                        [
                            // Nullable has a value
                            new CSharpExpressionStatement(new CSharpBinary("=", new CSharpIdentifier("(*pReturnValue)"), new CSharpUnary("*", new CSharpIdentifier("returnValue_interop")))),
                            new CSharpReturn(new CSharpLiteral("1"))
                        ],
                        [
                            // Nullable does not have a value
                            new CSharpReturn(new CSharpLiteral("0"))
                        ]
                    );

                    cppBody.Add(new CppVariableDeclaration(
                        cppInteropReturnType.GetFullyQualifiedName(),
                        "reinterop_returnValueIsValid",
                        new CppCall(new CppIdentifier(csFunctionName), cppCallArguments.ToArray())
                    ));
                    // TODO: convert from interop type. Even though it's not necessary?
                    cppBody.Add(new CppReturn(new CppRaw("reinterop_returnValueIsValid ? std::make_optional(reinterop_returnValue) : std::nullopt")));
                }
                else
                {
                    csInteropReturnType = CSharpType.FromSymbol(_context, _context.Compilation.GetSpecialType(SpecialType.System_Void));
                    cppInteropReturnType = CppType.Void.AsReturnType();
                    newReturnStatement = new CSharpExpressionStatement(new CSharpBinary(
                        "=",
                        new CSharpUnary("*", new CSharpIdentifier("pReturnValue")),
                        new CSharpIdentifier("returnValue_interop")
                    ));

                    cppBody.Add(new CppExpressionStatement(new CppCall(new CppIdentifier(csFunctionName), cppCallArguments.ToArray())));
                    cppBody.Add(new CppReturn(new CppIdentifier("reinterop_returnValue")));
                }

                bodyStatements = RewriteStructReturn(bodyStatements, csReturnType, "returnValue_interop", newReturnStatement);
            }
            else if (csReturnType.SpecialType != SpecialType.System_Void)
            {
                // Non-void return
                cppBody.Add(new CppReturn(cppReturnType.GetConversionFromInteropTypeExpression(_context, new CppCall(new CppIdentifier(csFunctionName), cppCallArguments.ToArray()))));
            }
            else
            {
                // Void return
                cppBody.Add(new CppExpressionStatement(new CppCall(new CppIdentifier(csFunctionName), cppCallArguments.ToArray())));
            }

            // Rewrite the body to convert from the interop parameter types to the C# parameter types, and
            // from the C# return type to the interop return type.
            if (csReturnType.SpecialType != SpecialType.System_Void)
                bodyStatements = RewriteReturnStatementToConvertToInterop(bodyStatements, csReturnType, csInteropReturnType);
            if (csInteropParameterConversions.Count > 0)
                bodyStatements = RewriteParametersToConvertFromInterop(bodyStatements, csInteropParameterConversions);

            // Always add an additional parameter for exception handling.
            CSharpType csInteropExceptionType = CSharpType.FromSymbol(_context, _context.Compilation.GetSpecialType(SpecialType.System_IntPtr)).AsPointer();
            CppType cppInteropExceptionType = CppType.VoidPointerPointer.AsParameterType();
            csInteropParameters.Add(new CSharpParameter(csInteropExceptionType, "reinteropException"));
            cppInteropParameters.Add(new CppParameter(cppInteropExceptionType, "reinteropException"));
            
            // Wrap the entire body in an exception handler
            CSharpReturn csReturnOnException;
            if (csInteropReturnType.SpecialType == SpecialType.System_Void)
                csReturnOnException = new CSharpReturn(null);
            else if (csInteropReturnType.Flags.HasFlag(CSharpTypeFlags.Pointer) || csInteropReturnType.Kind == InteropTypeKind.ClassWrapper)
                csReturnOnException = new CSharpReturn(new CSharpLiteral("null"));
            else
                csReturnOnException = new CSharpReturn(new CSharpNew(csInteropReturnType.GetFullyQualifiedName(), []));

            bodyStatements = [
                new CSharpTryCatch(
                    bodyStatements,
                    [
                        new CSharpExpressionStatement(new CSharpBinary(
                            "=",
                            new CSharpUnary("*", new CSharpIdentifier("reinteropException")),
                            new CSharpCall(new CSharpMemberAccess(new CSharpIdentifier("Reinterop.ObjectHandleUtility"), "CreateHandle"), [new CSharpIdentifier("reinteropManagedException")])
                        )),
                        csReturnOnException
                    ]
                )
            ];

            string interopParameterList = string.Join(", ", csInteropParameters.Select(p => p.Type.GetFullyQualifiedName() + " " + p.Name));
            string cppInteropParameterTypeList = string.Join(", ", cppInteropParameters.Select(p => p.Type.GetFullyQualifiedName()));
            IEnumerable<CppType> fieldPointerTypes = cppInteropParameters.Select(p => p.Type).Concat([ cppInteropReturnType ]);

            // The C# function that receives the call from C++.
            CSharpFunction csharpFunction = new CSharpFunction(_context, csOwner, csFunctionName)
                .ReturnType(csInteropReturnType)
                .Parameters(csInteropParameters)
                .Private(true)
                .Static(true)
                .Unsafe(true)
                .Attributes([$"[AOT.MonoPInvokeCallback(typeof({csFunctionName}_Type))]"])
                .Body(bodyStatements);

            // The C++ function that calls through to the C# function via the function pointer / delegate.
            CppFunction cppWrapper = new CppFunction(_context, cppOwner, _name)
                .TypeArguments(TypeArguments())
                .ReturnType(cppReturnType.AsReturnType())
                .Parameters(cppParameters.Select(p => new CppParameter(p.Type.AsParameterType(), p.Name)))
                .Private(Private())
                .Static(Static())
                .Specializes(Specializes())
                .DefinitionBody(cppBody);

            CppFunction functionPointer = new CppFunction(_context, cppOwner, "(*" + csFunctionName + ")")
                .TypeArguments(TypeArguments())
                .ReturnType(cppInteropReturnType)
                .Parameters(cppInteropParameters)
                .Private(true)
                .Static(true);

            return new InteropFunctions() { csharp = csharpFunction, cpp = cppWrapper, functionPointer = functionPointer };
        }

        public void GenerateCode(CppGenerationContext context, GeneratedResult result)
        {
            InteropFunctions functions = CreatePairedInteropFunctions();
            functions.functionPointer.AddToGeneration(result);
            functions.cpp.AddToGeneration(result);

            result.Init.Functions.Add(new GeneratedInitFunction(
                $"{result.Type.GetFullyQualifiedName()}::{functions.csharp.Name}",
                functions.functionPointer.GetFunctionPointerDeclaration(),
                functions.csharp.Name + "_Delegate",
                $$"""
                [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
                private {{functions.csharp.GetDelegateDeclaration(functions.csharp.Name + "_Type")}};
                private static unsafe readonly {{functions.csharp.Name}}_Type {{functions.csharp.Name}}_Delegate = new {{functions.csharp.Name}}_Type({{functions.csharp.Name}});
                {{functions.csharp.Print()}}
                """,
                CppTypeDeclarationsReferenced: [ .. functions.functionPointer.Parameters().Select(p => p.Type), functions.functionPointer.ReturnType() ],
                CppTypeDefinitionsReferenced: [ result.Type ]
            ));
        }

        private IEnumerable<CppStatement>? CreateCppWrapperImplementation(
            string functionPointerName,
            List<CppParameter> cppParameters,
            CppType cppReturnType,
            List<CppParameter> cppInteropParameters,
            CppType cppInteropReturnType)
        {
            CppExpression functionPointer = new CppIdentifier(functionPointerName);

            // Build the call arguments in the same order as the interop function pointer's
            // parameter list: thiz (if this is an instance function), then the actual
            // parameters converted to their interop form. The pReturnValue out-parameter (for a
            // struct-return rewrite) and reinteropException are handled below.
            List<CppArgument> arguments = new();

            if (!Static())
            {
                CppType cppOwnerParameterType = CppType.FromCSharp(_context, Owner()).AsParameterType();
                arguments.Add(CppArgument.Value(cppOwnerParameterType.GetConversionToInteropType(_context, "(*this)")));
            }

            foreach (CppParameter parameter in cppParameters)
            {
                CppType parameterType = parameter.Type.AsParameterType();
                arguments.Add(CppArgument.Value(parameterType.GetConversionToInteropType(_context, parameter.Name)));
            }

            const string resultVariableName = "result";

            if (NeedsStructReturnRewrite && ReturnType().Kind == InteropTypeKind.Nullable)
            {
                // The interop function returns a bool (whether the nullable has a value) and writes the
                // underlying value, if any, through the pReturnValue out-parameter.
                CppType elementType = cppReturnType.GenericArguments!.First();
                arguments.Add(CppArgument.OutParameter(elementType.GetFullyQualifiedName(), resultVariableName));
                string convertedResult = cppReturnType.GetConversionFromInteropType(_context, resultVariableName);
                return CppInterop.CallManagedFunction(
                    functionPointer,
                    arguments,
                    resultTypeName: "auto",
                    returnExpression: new CppRaw($"resultIsValid ? std::make_optional(std::move({convertedResult})) : std::nullopt"),
                    resultVariableName: "resultIsValid");
            }

            if (NeedsStructReturnRewrite)
                arguments.Add(CppArgument.OutParameter(cppReturnType.GetFullyQualifiedName(), resultVariableName));

            bool isVoid = cppReturnType.Name == "void" && !cppReturnType.Flags.HasFlag(CppTypeFlags.Pointer);
            if (isVoid)
                return CppInterop.CallManagedFunction(functionPointer, arguments);

            return CppInterop.CallManagedFunction(
                functionPointer,
                arguments,
                resultTypeName: NeedsStructReturnRewrite ? null : "auto",
                returnExpression: new CppRaw(cppReturnType.GetConversionFromInteropType(_context, resultVariableName)),
                resultVariableName: resultVariableName);
        }

        // Rewrites return statements to convert the actual C# return value to its interop form.
        private List<CSharpStatement> RewriteReturnStatementToConvertToInterop(IEnumerable<CSharpStatement> statements, CSharpType returnType, CSharpType interopReturnType)
        {
            List<CSharpStatement> result = statements.Select(statement =>
            {
                return statement switch
                {
                    CSharpReturn r => new CSharpReturn(returnType.GetConversionToInteropTypeExpression(r.Value!)),
                    CSharpIf i => new CSharpIf(i.Condition, RewriteReturnStatementToConvertToInterop(i.Then, returnType, interopReturnType)),
                    CSharpStatement s => s
                };
            }).ToList();
            return result;
        }

        private List<CSharpStatement> RewriteParametersToConvertFromInterop(IEnumerable<CSharpStatement> statements, Dictionary<string, CSharpExpression> parameterConversions)
        {
            List<CSharpStatement> result = statements.Select(statement =>
            {
                return statement switch
                {
                    CSharpVariableDeclaration d => new CSharpVariableDeclaration(d.TypeName, d.Name, RewriteExpressionToConvertFromInterop(d.Initializer, parameterConversions)),
                    CSharpExpressionStatement s => new CSharpExpressionStatement(RewriteExpressionToConvertFromInterop(s.Expression, parameterConversions)!),
                    CSharpIf i => new CSharpIf(i.Condition, RewriteParametersToConvertFromInterop(i.Then, parameterConversions)),
                    CSharpThrow t => new CSharpThrow(RewriteExpressionToConvertFromInterop(t.Exception, parameterConversions)!),
                    CSharpReturn r => new CSharpReturn(RewriteExpressionToConvertFromInterop(r.Value, parameterConversions)),
                    CSharpTryCatch t => new CSharpTryCatch(RewriteParametersToConvertFromInterop(t.TryBody, parameterConversions), RewriteParametersToConvertFromInterop(t.CatchBody, parameterConversions)),
                    _ => statement
                };
            }).ToList();
            return result;
        }

        private CSharpExpression? RewriteExpressionToConvertFromInterop(CSharpExpression? expression, Dictionary<string, CSharpExpression> parameterConversions)
        {
            if (expression == null)
                return null;

            return expression switch
            {
                CSharpIdentifier i => RewriteIdentifierToConvertFromInterop(i, parameterConversions),
                CSharpCall c => new CSharpCall(RewriteExpressionToConvertFromInterop(c.Callee, parameterConversions)!, c.Arguments.Select(a => RewriteExpressionToConvertFromInterop(a, parameterConversions)!).ToArray()),
                CSharpTernary t => new CSharpTernary(RewriteExpressionToConvertFromInterop(t.Condition, parameterConversions)!, RewriteExpressionToConvertFromInterop(t.Then, parameterConversions)!, RewriteExpressionToConvertFromInterop(t.Else, parameterConversions)!),
                CSharpBinary b => new CSharpBinary(b.Op, RewriteExpressionToConvertFromInterop(b.Left, parameterConversions)!, RewriteExpressionToConvertFromInterop(b.Right, parameterConversions)!),
                CSharpUnary u => new CSharpUnary(u.Op, RewriteExpressionToConvertFromInterop(u.Operand, parameterConversions)!),
                CSharpIs i => new CSharpIs(RewriteExpressionToConvertFromInterop(i.Expression, parameterConversions)!, i.TypeName, i.castedVariableName),
                CSharpMemberAccess m => new CSharpMemberAccess(RewriteExpressionToConvertFromInterop(m.Target, parameterConversions)!, m.MemberName),
                CSharpElementAccess e => new CSharpElementAccess(RewriteExpressionToConvertFromInterop(e.Target, parameterConversions)!, e.Arguments.Select(a => RewriteExpressionToConvertFromInterop(a, parameterConversions)!).ToArray()),
                CSharpNew n => new CSharpNew(n.TypeName, n.Arguments.Select(a => RewriteExpressionToConvertFromInterop(a, parameterConversions)!).ToArray()),
                CSharpCast c => new CSharpCast(c.TypeName, RewriteExpressionToConvertFromInterop(c.Expression, parameterConversions)!),
                _ => expression
            };
        }

        private CSharpExpression RewriteIdentifierToConvertFromInterop(CSharpIdentifier identifier, Dictionary<string, CSharpExpression> parameterConversions)
        {
            if (!parameterConversions.TryGetValue(identifier.Name, out CSharpExpression? conversion))
                return identifier;
            return conversion;
        }

        // Rewrites a C# function body like this:
        //   return thiz.SomeFunction(whatever);
        // into a body like this:
        //   SomeType returnValue_interop = thiz.SomeFunction(whatever);
        //   *pReturnValue = returnValue;
        // Where "returnValue_interop" is the string passed to the `returnValueName parameter, and "*pReturnValue = returnValue" is the statement passed
        // to the `newReturnStatement` parameter.
        // This function handles more complicated bodies with multiple return statements (e.g., if statements), and will throw an exception if it
        // encounters a return statement that doesn't return a value when the function has a non-void return type.
        private List<CSharpStatement> RewriteStructReturn(IEnumerable<CSharpStatement> statements, CSharpType returnType, string returnValueName, CSharpStatement newReturnStatement)
        {
            List<CSharpStatement> result = statements.SelectMany(statement =>
            {
                return statement switch
                {
                    CSharpReturn { Value: null } => throw new InvalidOperationException($"Cannot generate C# code for a CSharpFunctionCallableFromCpp ${GetDisplayName()} because it has a struct return type but has a void return statement."),
                    CSharpReturn r => new List<CSharpStatement> {
                        new CSharpVariableDeclaration(returnType.GetFullyQualifiedName(), returnValueName, r.Value),
                        newReturnStatement
                    },
                    CSharpIf i => [new CSharpIf(i.Condition, RewriteStructReturn(i.Then, returnType, returnValueName, newReturnStatement))],
                    CSharpStatement s => [s]
                };
            }).ToList();
            return result;
        }
    }
}
