#include "Cesium3DTileset.h"

using namespace CesiumForUnity;

CESIUM_FOR_UNITY_CESIUM3DTILESET_DEFAULT_CONTENTS_DEFINITION
CESIUM_FOR_UNITY_CESIUM3DTILESET_DEFAULT_CONSTRUCTOR_DEFINITION

void Cesium3DTileset::Update() {

}